
export interface AffiliateLink {
  keyword: string;
  url: string;
  label: string;
  description: string;
}

export const AFFILIATE_LINKS: AffiliateLink[] = [
  { keyword: 'Shopify', url: 'https://shopify.pxf.io/autowealth', label: 'Shopify (Special Offer)', description: '$1/month for 3 months' },
  { keyword: 'hosting', url: 'https://bluehost.sjv.io/autowealth', label: 'Bluehost', description: '60% OFF Hosting' },
  { keyword: 'domain', url: 'https://namecheap.pxf.io/autowealth', label: 'Namecheap', description: 'Domains from $0.99' },
  { keyword: 'email marketing', url: 'https://convertkit.com?lmref=autowealth', label: 'ConvertKit', description: 'Free for 1000 subscribers' },
  { keyword: 'automation', url: 'https://make.com?pc=autowealth', label: 'Make.com', description: 'Best Automation Tool' },
  { keyword: 'SEO', url: 'https://semrush.sjv.io/autowealth', label: 'Semrush', description: '7-day Free Trial' },
  { keyword: 'AI writer', url: 'https://jasper.ai?fpr=autowealth', label: 'Jasper AI', description: '10k Free Words' },
  { keyword: 'video editor', url: 'https://invideo.io?ref=autowealth', label: 'InVideo', description: 'AI Video Creation' },
];

export const processActionPlan = (plan: string[]): { text: string; links: AffiliateLink[] }[] => {
  return plan.map(step => {
    const matchedLinks: AffiliateLink[] = [];
    AFFILIATE_LINKS.forEach(link => {
      if (step.toLowerCase().includes(link.keyword.toLowerCase())) {
        matchedLinks.push(link);
      }
    });
    return { text: step, links: matchedLinks };
  });
};

export const generateBusinessPlan = (opportunity: any, language: 'en' | 'zh') => {
  const t = {
    title: language === 'zh' ? '商业计划书' : 'BUSINESS PLAN',
    generatedBy: language === 'zh' ? '由 AutoWealth Scout AI 生成' : 'Generated by AutoWealth Scout AI',
    overview: language === 'zh' ? '项目概览' : 'EXECUTIVE SUMMARY',
    revenue: language === 'zh' ? '预估收入' : 'ESTIMATED REVENUE',
    difficulty: language === 'zh' ? '执行难度' : 'DIFFICULTY',
    actionPlan: language === 'zh' ? '执行计划' : 'ACTION PLAN',
    validation: language === 'zh' ? '市场验证' : 'MARKET VALIDATION',
    competitors: language === 'zh' ? '竞争对手' : 'COMPETITORS',
    tools: language === 'zh' ? '推荐工具' : 'RECOMMENDED TOOLS',
  };

  const tools = AFFILIATE_LINKS.map(l => `- ${l.label}: ${l.url} (${l.description})`).join('\n');

  const content = `
# ${t.title}: ${opportunity.title}
> ${t.generatedBy} - ${new Date().toLocaleDateString()}

## ${t.overview}
${opportunity.description}

- ${t.revenue}: ${opportunity.estimatedMonthlyRevenue}
- ${t.difficulty}: ${opportunity.difficulty}
- Automation Score: ${opportunity.automationScore}/100

## ${language === 'zh' ? '技术实操 (CRITICAL)' : 'TECHNICAL IMPLEMENTATION'}
${opportunity.technicalImplementation ? `
### ${language === 'zh' ? '数据源' : 'Data Sources'}
${opportunity.technicalImplementation.dataSources?.map((s: string) => `- ${s}`).join('\n')}

### ${language === 'zh' ? '核心脚本逻辑' : 'Script Function'}
> ${opportunity.technicalImplementation.scriptFunction}

### ${language === 'zh' ? '分步指南' : 'Step-by-Step Guide'}
${opportunity.technicalImplementation.stepByStepGuide?.map((s: string, i: number) => `${i + 1}. ${s}`).join('\n')}
` : 'N/A'}

## ${language === 'zh' ? '变现与平台' : 'MONETIZATION & PLATFORMS'}
**${language === 'zh' ? '目标平台' : 'Target Platforms'}:**
${opportunity.targetPlatforms?.map((p: string) => `- ${p}`).join('\n')}

**${language === 'zh' ? '变现策略' : 'Monetization Strategy'}:**
${opportunity.monetizationStrategy?.map((s: string) => `- ${s}`).join('\n')}

## ${t.validation}
${opportunity.validationEvidence?.map((e: any) => `- [${e.type}] ${e.content}`).join('\n') || 'N/A'}

## ${t.actionPlan}
${opportunity.actionPlan?.map((step: string, i: number) => `${i + 1}. ${step}`).join('\n')}

## ${t.competitors}
${opportunity.competitors?.map((c: string) => `- ${c}`).join('\n')}

## ${t.tools}
${tools}

---
Generated by AutoWealth Scout AI
  `.trim();

  return content;
};
